---
version: 2.1
orbs:
  go: circleci/go@1.10
jobs:
  build:
    docker:
      - image: cimg/go:<< parameters.tag >>
    parameters:
      tag:
        type: string
    environment:
      GOOS: 'linux'
      GOARCH: 'amd64'
      ARTIFACTS: /tmp/artifacts
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout: {}
      - run:
          name: Setup test environment
          command: |
            mkdir -p "${ARTIFACTS}"
            mkdir -p "${TEST_RESULTS}/junit"
      - go/load-cache: {}
      - go/mod-download: {}
      - go/save-cache: {}
      - run:
          name: Run unit tests
          command: |
            gotestsum \
              --junitfile "${TEST_RESULTS}/junit.xml" \
              -- \
              -race \
              -coverprofile="${ARTIFACTS}/coverage.out" \
              ./...
            go tool cover \
              -html="${ARTIFACTS}/coverage.out" \
              -o "${ARTIFACTS}/coverage.html"
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build:
    jobs:
      - build:
          name: build-go<< matrix.tag >>
          matrix:
            parameters:
              tag:
                - "1.20"
                - "1.21"
